[package]
name = "yarg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiled = "0.11.1"


[dependencies.raylib]
version = "3.7.0"
